<?php

/**
 * ProcessWire module that lets you limit the list of available templates for new pages
 * based on the parent page(s).
 *
 * Only works in conjunction with ProcessTemplateParents.
 *
 * (c) 2016 BitPoet
 * Licensed under MPLv2
 *
 */

class TemplateParents extends WireData implements Module {
	public static function getModuleInfo() {
		return array(
			"title"			=>	"Template Parents",
			"summary"		=>	"Module for parent-based template management.",
			"version"		=>	"0.0.6",
			"installs"		=>	array("ProcessTemplateParents"),
			"autoload"		=>	true,
		);
	}
	
	public function init() {
		$this->addHookAfter("Templates::deleted", $this, "templateDeleted");
		$this->addHookAfter("ProcessPageAdd::getAllowedTemplates", $this, "filterAllowedParents");
		// Hooks for editing directly on the template:
		$this->addHookAfter("ProcessTemplate::buildEditForm", $this, "appendFieldToForm");
		$this->addHookBefore("ProcessTemplate::saveTemplate", $this, "saveCustomFields");
	}
	
	public function templateDeleted($event) {
		$process = $this->modules->get("ProcessTemplateParents");
		$template = $event->arguments(0);
		$process->deleteTemplateAssignment($template->id);
	}

	public function filterAllowedParents($event) {
		$process = $this->modules->get("ProcessTemplateParents");

		$parent = $event->arguments(0);
		if(! $parent) {
			$parent = wire('pages')->get((int)$this->input->get->parent_id);
		}
		if(! $parent) {
			$parent = wire('pages')->get((int)$this->input->post->parent_id);
		}
		if($parent instanceof NullPage) return;
		
		$templates = $event->return;
		$out = array();
		foreach($templates as $template) {
			$allowed = $process->getTemplateParents($template);
			if(count($allowed) == 0) {
				$out[$template->id] = $template;
			} else if(in_array($parent->id, $allowed)) {
				$out[$template->id] = $template;
			} else if($process->inheritSettings == 1) {
				foreach($allowed as $allowedId) {
					$allowedPage = $this->pages->get($allowedId);
					if($parent->parents->has($allowedPage)) {
						$out[$template->id] = $template;
						break 1;
					}
				}
			}
		}
		$event->return = $out;
	}

	public function appendFieldToForm($event) {
		$process = $this->modules->get("ProcessTemplateParents");
		
		$proctpl = $event->object;
		$frm = $event->return;
		$tpl = $event->arguments(0);
		
		$allowed = $process->getTemplateParents($tpl);
		
		$field = $this->modules->get('InputfieldPageListSelectMultiple'); 
		$field->attr('name', 'allowedParents'); 
		$field->collapsed = count($allowed) ? Inputfield::collapsedNo : Inputfield::collapsedYes; 
		$field->label = $this->_('Allowed page(s) for parent');
		$field->description = $this->_('Select pages under which new pages with this template may be added.');
		$field->description .= ' ' . $this->_("If no pages are selected, no limitation is placed on new pages, though other family restrictions still apply.");
		$field->attr('value', $allowed);
		
		$familyWrap = $frm->find('id=family')->first();
		$familyWrap->insertAfter($field, $familyWrap->get('parentTemplates'));
	}

	public function saveCustomFields($event) {
		$form = $event->arguments(0);
		$tpl  = $event->arguments(1);
		
		$a = array();
		if(is_array($this->input->post->allowedParents)) { // foreach($this->input->post->allowedParents as $id) $a[] = (int) $id;
			$vals = explode(',', $this->input->post->allowedParents[0]);
			$a = array_map(function($v) { return trim($v); }, $vals);
		}

		$process = $this->modules->get("ProcessTemplateParents");
		$process->saveTemplateParents($tpl->id, wireEncodeJSON($a));
	}
	
}
